[server]
listen_port = 8080

[common]
;; false: 所有443端口都纯转发数据
;; true : 所有443端口先进行tls解密再转发
parse_tls = true

;; false: 纯转发数据 && 如果 parse_tls=true 的话, 443端口的数据先tls解密后再转发
;; true : 解析并重构所有的http数据 && parse_tls=true的话, 443端口的数据先tls解密后再进行http解析并重构
parse_http = false

;; 日志输出的地方, [console, file, null]
log_to = file

[tls]
crt_path = .\tls\tls.crt
key_path = .\tls\tls.key
